import { NextRequest, NextResponse } from 'next/server';
import { platformDb, getTenantPrisma } from '@pixeesite/database';
import { requireOrgMember } from '@/lib/auth-helpers';
import { aiCall } from '@/lib/ai-client';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 60;

/**
 * POST /api/orgs/[slug]/sites/[siteSlug]/seo/auto
 * Body: { pageId?: string, all?: boolean }
 *
 * Génère automatiquement title/description meta pour 1 page ou toutes les pages
 * dont meta.description est vide. Utilise les blocs (titres, texte) comme contexte.
 */
export async function POST(req: NextRequest, { params }: { params: Promise<{ slug: string; siteSlug: string }> }) {
  const { slug, siteSlug } = await params;
  let auth;
  try { auth = await requireOrgMember(slug, ['owner', 'admin', 'editor']); } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 403 });
  }

  const body = await req.json().catch(() => ({}));
  const targetPageId: string | undefined = body.pageId;
  const all: boolean = !!body.all;

  const site = await platformDb.site.findUnique({
    where: { orgId_slug: { orgId: auth.membership.org.id, slug: siteSlug } },
    select: { id: true, name: true },
  });
  if (!site) return NextResponse.json({ error: 'site-not-found' }, { status: 404 });

  const db = await getTenantPrisma(slug);
  const pages = targetPageId
    ? await db.sitePage.findMany({ where: { id: targetPageId, siteId: site.id } })
    : await db.sitePage.findMany({ where: { siteId: site.id } });

  const results: any[] = [];
  for (const page of pages) {
    const meta: any = page.meta || {};
    if (!all && meta.description && meta.title) {
      results.push({ pageId: page.id, skipped: 'already-has-meta' });
      continue;
    }

    // Extrait du contenu textuel des blocs pour le contexte
    const blocks: any[] = Array.isArray(page.blocks) ? page.blocks as any[] : [];
    const excerpt = blocks
      .map((b: any) => {
        if (b?.data?.title) return String(b.data.title);
        if (b?.data?.subtitle) return String(b.data.subtitle);
        if (b?.data?.html) return String(b.data.html).replace(/<[^>]+>/g, ' ').slice(0, 200);
        return '';
      })
      .filter(Boolean)
      .join(' • ')
      .slice(0, 800);

    const prompt = `Tu es un expert SEO. Génère un title (≤60 caractères) et une meta description (≤160 caractères) en français pour cette page web.\n\nSite: ${site.name}\nPage: ${page.title}\nURL: ${page.slug}\nExtrait du contenu: ${excerpt || '(vide)'}\n\nRéponds UNIQUEMENT en JSON: {"title":"…","description":"…"}`;
    const r = await aiCall({
      orgId: auth.membership.org.id,
      feature: 'seo-meta',
      prompt,
      temperature: 0.5,
      maxTokens: 300,
    });

    if (!r.ok || !r.output) {
      results.push({ pageId: page.id, error: r.error || 'no-output' });
      continue;
    }

    // Extract JSON from output
    let parsed: { title?: string; description?: string } = {};
    try {
      const match = String(r.output).match(/\{[\s\S]*\}/);
      if (match) parsed = JSON.parse(match[0]);
    } catch {
      // Fall through with empty parsed
    }

    const newMeta = {
      ...meta,
      ...(parsed.title && !meta.title ? { title: parsed.title.slice(0, 70) } : {}),
      ...(parsed.description ? { description: parsed.description.slice(0, 180) } : {}),
      seoAutoGenerated: true,
      seoAutoAt: new Date().toISOString(),
    };
    await db.sitePage.update({ where: { id: page.id }, data: { meta: newMeta } });
    results.push({ pageId: page.id, slug: page.slug, meta: newMeta });
  }

  return NextResponse.json({ ok: true, results });
}
